export let girlsData = [
    {
        name: "Alina",
        status: "Жду звонка",
        descr: "Пример описания текста",
        src: "assets/img/anketa.jpg",
        srcCheck: "assets/img/100.png",
        likes: "3",
        phone: "8 (111) 111-11-11",
        age: "18",
        weight: "56",
        growth: "175",
        breast: "3",
        priceHour: "1500 Р",
        priceTwoHour: "3000 Р",
        priceNight: "7500 Р",
    },
    {
        name: "Masha",
        status: "Жду звонка",
        descr: "Пример описания текста",
        src: "assets/img/anketa.jpg",
        srcCheck: "assets/img/100.png",
        likes: "5",
        phone: "8 (111) 111-11-11",
        age: "21",
        weight: "51",
        growth: "181",
        breast: "2",
        priceHour: "2000 Р",
        priceTwoHour: "3500 Р",
        priceNight: "9000 Р",
    },
    {
        name: "Nastya",
        status: "Занята",
        descr: "Пример описания текста",
        src: "assets/img/anketa.jpg",
        srcCheck: "assets/img/100.png",
        likes: "1",
        phone: "8 (111) 111-11-11",
        age: "20",
        weight: "50",
        growth: "170",
        breast: "1",
        priceHour: "1000 Р",
        priceTwoHour: "2000 Р",
        priceNight: "5000 Р",
    },
    {
        name: "Vera",
        status: "Жду звонка",
        descr: "Пример описания текста",
        src: "assets/img/anketa.jpg",
        srcCheck: "assets/img/100.png",
        likes: "7",
        phone: "8 (111) 111-11-11",
        age: "23",
        weight: "54",
        growth: "176",
        breast: "2",
        priceHour: "3000 Р",
        priceTwoHour: "6000 Р",
        priceNight: "12000 Р",
    }
];